name: Build and Release
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      tag:
        description: '当前版本号'
        required: true
        type: string
        default: 'v1.0.0'

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, macos, windows]
        include:
          - build: linux
            os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-musl
            archive-name: tweers-linux.tar.gz
          - build: linux-arm64
            os: ubuntu-latest
            rust: stable
            target: aarch64-unknown-linux-musl
            archive-name: tweers-linux-arm64.tar.gz
          - build: macos
            os: macos-latest
            rust: stable
            target: x86_64-apple-darwin
            archive-name: tweers-macos.tar.gz
          - build: windows
            os: windows-latest
            rust: stable
            target: x86_64-pc-windows-msvc
            archive-name: tweers-windows.7z
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.target }}

      - name: Build binary
        run: cargo build --verbose --release --target ${{ matrix.target }}
        env:
          RUST_BACKTRACE: 1

      - name: Strip binary (linux and macos)
        if: matrix.build == 'linux' || matrix.build == 'macos'
        run: strip "target/${{ matrix.target }}/release/tweers"

      - name: Build archive
        shell: bash
        run: |
          mkdir archive
          if [ -f "LICENSE" ]; then cp LICENSE archive/; fi
          if [ -f "README.md" ]; then cp README.md archive/; fi
          if [ -d "test/story-format" ]; then cp -r test/story-format archive/; fi
          cd archive
          if [ "${{ matrix.build }}" = "windows" ]; then
            cp "../target/${{ matrix.target }}/release/tweers.exe" ./
            if [ -d "story-format" ]; then
              7z a "${{ matrix.archive-name }}" LICENSE README.md story-format tweers.exe
            else
              7z a "${{ matrix.archive-name }}" LICENSE README.md tweers.exe
            fi
          else
            cp "../target/${{ matrix.target }}/release/tweers" ./
            if [ -d "story-format" ]; then
              tar -czf "${{ matrix.archive-name }}" LICENSE README.md story-format tweers
            else
              tar -czf "${{ matrix.archive-name }}" LICENSE README.md tweers
            fi
          fi

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.archive-name }}
          path: archive/${{ matrix.archive-name }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          pattern: "tweers-*"
          merge-multiple: false
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag || github.ref_name }}
          files: |
            ./artifacts/tweers-linux.tar.gz/tweers-linux.tar.gz
            ./artifacts/tweers-macos.tar.gz/tweers-macos.tar.gz
            ./artifacts/tweers-windows.7z/tweers-windows.7z
          draft: false
          prerelease: false
