name: Build and Release
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      tag:
        description: '当前版本号'
        required: true
        type: string
        default: 'v1.0.0'

jobs:
  build:
    name: Build - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            archive-name: tweers-linux-x86_64.tar.gz

          - os-name: macOS-x86_64
            runs-on: macos-latest
            target: x86_64-apple-darwin
            archive-name: tweers-macos-x86_64.tar.gz

          - os-name: macOS-arm64
            runs-on: macos-latest
            target: aarch64-apple-darwin
            archive-name: tweers-macos-arm64.tar.gz

          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc
            archive-name: tweers-windows-x86_64.zip

      fail-fast: false

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - name: Build archive
        shell: bash
        run: |
          mkdir archive
          if [ -f "LICENSE" ]; then cp LICENSE archive/; fi
          if [ -f "README.md" ]; then cp README.md archive/; fi
          if [ -d "test/story-format" ]; then cp -r test/story-format archive/; fi
          cd archive
          if [ "${{ matrix.platform.target }}" = "x86_64-pc-windows-msvc" ]; then
            cp "../target/${{ matrix.platform.target }}/release/tweers.exe" ./
            if [ -d "story-format" ]; then
              zip -r "${{ matrix.platform.archive-name }}" LICENSE README.md story-format tweers.exe
            else
              zip -r "${{ matrix.platform.archive-name }}" LICENSE README.md tweers.exe
            fi
          else
            cp "../target/${{ matrix.platform.target }}/release/tweers" ./
            if [ -d "story-format" ]; then
              tar -czf "${{ matrix.platform.archive-name }}" LICENSE README.md story-format tweers
            else
              tar -czf "${{ matrix.platform.archive-name }}" LICENSE README.md tweers
            fi
          fi

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.archive-name }}
          path: archive/${{ matrix.platform.archive-name }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          pattern: "tweers-*"
          merge-multiple: false
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag || github.ref_name }}
          files: |
            ./artifacts/tweers-linux-x86_64.tar.gz/tweers-linux-x86_64.tar.gz
            ./artifacts/tweers-macos-x86_64.tar.gz/tweers-macos-x86_64.tar.gz
            ./artifacts/tweers-macos-arm64.tar.gz/tweers-macos-arm64.tar.gz
            ./artifacts/tweers-windows-x86_64.zip/tweers-windows-x86_64.zip
          draft: false
          prerelease: false
